(define (problem waymo-problem)
 (:domain waymo-domain)
 (:objects
   waymo_01 - waymo
   stop_0 stop_1 stop_2 stop_3 stop_4 stop_5 stop_6 stop_7 stop_8 stop_9 stop_10 stop_11 stop_12 stop_13 stop_14 stop_15 stop_16 stop_17 stop_18 stop_19 stop_20 stop_21 stop_22 stop_23 stop_24 stop_25 stop_26 stop_27 stop_28 stop_29 stop_30 stop_31 - location
   passenger_01 - passenger
 )
 (:init
              (waymo_at waymo_01 stop_0)
              (passenger_at passenger_01 stop_0)
              (connected stop_0 stop_1)
              (connected stop_1 stop_0)
              (connected stop_1 stop_2)
              (connected stop_2 stop_1)
              (connected stop_2 stop_3)
              (connected stop_3 stop_2)
              (connected stop_3 stop_4)
              (connected stop_4 stop_3)
              (connected stop_4 stop_5)
              (connected stop_5 stop_4)
              (connected stop_5 stop_6)
              (connected stop_6 stop_5)
              (connected stop_6 stop_7)
              (connected stop_7 stop_6)
              (connected stop_7 stop_8)
              (connected stop_8 stop_7)
              (connected stop_8 stop_9)
              (connected stop_9 stop_8)
              (connected stop_9 stop_10)
              (connected stop_10 stop_9)
              (connected stop_10 stop_11)
              (connected stop_11 stop_10)
              (connected stop_11 stop_12)
              (connected stop_12 stop_11)
              (connected stop_12 stop_13)
              (connected stop_13 stop_12)
              (connected stop_13 stop_14)
              (connected stop_14 stop_13)
              (connected stop_14 stop_15)
              (connected stop_15 stop_14)
              (connected stop_15 stop_16)
              (connected stop_16 stop_15)
              (connected stop_16 stop_17)
              (connected stop_17 stop_16)
              (connected stop_17 stop_18)
              (connected stop_18 stop_17)
              (connected stop_18 stop_19)
              (connected stop_19 stop_18)
              (connected stop_19 stop_20)
              (connected stop_20 stop_19)
              (connected stop_20 stop_21)
              (connected stop_21 stop_20)
              (connected stop_21 stop_22)
              (connected stop_22 stop_21)
              (connected stop_22 stop_23)
              (connected stop_23 stop_22)
              (connected stop_23 stop_24)
              (connected stop_24 stop_23)
              (connected stop_24 stop_25)
              (connected stop_25 stop_24)
              (connected stop_25 stop_26)
              (connected stop_26 stop_25)
              (connected stop_26 stop_27)
              (connected stop_27 stop_26)
              (connected stop_27 stop_28)
              (connected stop_28 stop_27)
              (connected stop_28 stop_29)
              (connected stop_29 stop_28)
              (connected stop_29 stop_30)
              (connected stop_30 stop_29)
              (connected stop_30 stop_31)
              (connected stop_31 stop_30)
 )
 (:goal (and 
           (passenger_at passenger_01 stop_31)
        )
 )
)
