(define (problem waymo_2_electric_boogaloo-problem)
 (:domain waymo_2_electric_boogaloo-domain)
 (:objects
   waymo - waymo_0
   stop_0 stop_n_1 stop_n_2 stop_n_3 stop_n_4 stop_n_5 stop_n_6 stop_n_7 stop_n_8 stop_n_9 stop_s_1 stop_s_2 stop_s_3 stop_s_4 stop_s_5 stop_s_6 stop_s_7 stop_s_8 stop_s_9 stop_e_1 stop_e_2 stop_e_3 stop_e_4 stop_e_5 stop_e_6 stop_e_7 stop_e_8 stop_e_9 stop_w_1 stop_w_2 stop_w_3 stop_w_4 stop_w_5 stop_w_6 stop_w_7 stop_w_8 stop_w_9 - location
   passenger_0 passenger_1 - passenger
 )
 (:init
              (connected stop_0 stop_n_1)
              (connected stop_n_1 stop_0)
              (connected stop_n_1 stop_n_2)
              (connected stop_n_2 stop_n_1)
              (connected stop_n_2 stop_n_3)
              (connected stop_n_3 stop_n_2)
              (connected stop_n_3 stop_n_4)
              (connected stop_n_4 stop_n_3)
              (connected stop_n_4 stop_n_5)
              (connected stop_n_5 stop_n_4)
              (connected stop_n_5 stop_n_6)
              (connected stop_n_6 stop_n_5)
              (connected stop_n_6 stop_n_7)
              (connected stop_n_7 stop_n_6)
              (connected stop_n_7 stop_n_8)
              (connected stop_n_8 stop_n_7)
              (connected stop_n_8 stop_n_9)
              (connected stop_n_9 stop_n_8)
              (connected stop_0 stop_s_1)
              (connected stop_s_1 stop_0)
              (connected stop_s_1 stop_s_2)
              (connected stop_s_2 stop_s_1)
              (connected stop_s_2 stop_s_3)
              (connected stop_s_3 stop_s_2)
              (connected stop_s_3 stop_s_4)
              (connected stop_s_4 stop_s_3)
              (connected stop_s_4 stop_s_5)
              (connected stop_s_5 stop_s_4)
              (connected stop_s_5 stop_s_6)
              (connected stop_s_6 stop_s_5)
              (connected stop_s_6 stop_s_7)
              (connected stop_s_7 stop_s_6)
              (connected stop_s_7 stop_s_8)
              (connected stop_s_8 stop_s_7)
              (connected stop_s_8 stop_s_9)
              (connected stop_s_9 stop_s_8)
              (connected stop_0 stop_e_1)
              (connected stop_e_1 stop_0)
              (connected stop_e_1 stop_e_2)
              (connected stop_e_2 stop_e_1)
              (connected stop_e_2 stop_e_3)
              (connected stop_e_3 stop_e_2)
              (connected stop_e_3 stop_e_4)
              (connected stop_e_4 stop_e_3)
              (connected stop_e_4 stop_e_5)
              (connected stop_e_5 stop_e_4)
              (connected stop_e_5 stop_e_6)
              (connected stop_e_6 stop_e_5)
              (connected stop_e_6 stop_e_7)
              (connected stop_e_7 stop_e_6)
              (connected stop_e_7 stop_e_8)
              (connected stop_e_8 stop_e_7)
              (connected stop_e_8 stop_e_9)
              (connected stop_e_9 stop_e_8)
              (connected stop_0 stop_w_1)
              (connected stop_w_1 stop_0)
              (connected stop_w_1 stop_w_2)
              (connected stop_w_2 stop_w_1)
              (connected stop_w_2 stop_w_3)
              (connected stop_w_3 stop_w_2)
              (connected stop_w_3 stop_w_4)
              (connected stop_w_4 stop_w_3)
              (connected stop_w_4 stop_w_5)
              (connected stop_w_5 stop_w_4)
              (connected stop_w_5 stop_w_6)
              (connected stop_w_6 stop_w_5)
              (connected stop_w_6 stop_w_7)
              (connected stop_w_7 stop_w_6)
              (connected stop_w_7 stop_w_8)
              (connected stop_w_8 stop_w_7)
              (connected stop_w_8 stop_w_9)
              (connected stop_w_9 stop_w_8)
              (waymo_at waymo stop_0)
              (passenger_at passenger_0 stop_n_9)
              (passenger_at passenger_1 stop_s_9)
 )
 (:goal (and 
           (passenger_at passenger_0 stop_s_9)
           (passenger_at passenger_1 stop_e_9)
        )
 )
)
