(define (problem waymo-problem)
 (:domain waymo-domain)
 (:objects
   waymo - waymo_0
   stop_0 stop_1 stop_2 stop_3 stop_4 stop_5 stop_6 stop_7 stop_8 stop_9 stop_10 stop_11 stop_12 stop_13 stop_14 stop_15 - location
   passenger - passenger_0
 )
 (:init
              (waymo_at waymo stop_0)
              (passenger_at passenger stop_0)
              (connected stop_0 stop_1)
              (connected stop_1 stop_0)
              (connected stop_1 stop_2)
              (connected stop_2 stop_1)
              (connected stop_2 stop_3)
              (connected stop_3 stop_2)
              (connected stop_3 stop_4)
              (connected stop_4 stop_3)
              (connected stop_4 stop_5)
              (connected stop_5 stop_4)
              (connected stop_5 stop_6)
              (connected stop_6 stop_5)
              (connected stop_6 stop_7)
              (connected stop_7 stop_6)
              (connected stop_7 stop_8)
              (connected stop_8 stop_7)
              (connected stop_8 stop_9)
              (connected stop_9 stop_8)
              (connected stop_9 stop_10)
              (connected stop_10 stop_9)
              (connected stop_10 stop_11)
              (connected stop_11 stop_10)
              (connected stop_11 stop_12)
              (connected stop_12 stop_11)
              (connected stop_12 stop_13)
              (connected stop_13 stop_12)
              (connected stop_13 stop_14)
              (connected stop_14 stop_13)
              (connected stop_14 stop_15)
              (connected stop_15 stop_14)
 )
 (:goal (and 
           (passenger_at passenger stop_15)
        )
 )
)
